const express = require("express")
const mongo = require('./mongo')
const bodyParser = require('body-parser')
const app = express()
const cors = require('cors')
const morgan = require('morgan')
const UserRouter = require('./router')
app.use(express.json())
app.use(bodyParser.json())
app.use(morgan("tiny"))
app.use(cors())
mongo.connectToServer((err) => {
    if (err) console.log(err)
    else console.log('connected to server!!!')
})
app.use('/', UserRouter)
const port = 3001
app.listen(port, () => console.log("app running in port " + port))